Update sql.conf
BlueMap-Minecraft/BlueMap pull request #433
Opened 2023-05-17 22:44 UTC by Modog500000

Add
"# You still need to change your file type to sql in maps!" to sql.conf

2023-05-17 22:55 UTC, Chicken requested changes

2023-05-17 22:55 UTC, Chicken commented on BlueMapCommon/src/main/resources/de/bluecolored/bluemap/config/storages/sql.conf
> +# You still need to change your file type to sql in maps!
```suggestion
# You still need to change your storage type to sql in your map configs!
```

2023-05-18 00:15 UTC, TBlueF commented
A comment on the one storage-option that shouldn't be touched, doesn't seem to be placed very well to me tbh :D
I'll think about a better place for this :)

2023-08-21 19:41 UTC, TBlueF commented
Updated the wiki with a new page that explains the whole storage thing a bit more. This should be enough. :)

2023-08-21 19:41 UTC, closed without merging