Added missing signs
BlueMap-Minecraft/BlueMap pull request #536
Opened 2024-05-01 15:22 UTC by TyBraniff

Added Cherry and Bamboo signs.

2024-05-03 22:11 UTC, TyBraniff commented
Updated to include everything from my fixes resource pack which should satisfy most of https://github.com/BlueMap-Minecraft/BlueMap/issues/145 

Not sure I'm doing these pull requests right, hopefully its all copasetic. 

[Live Examples](https://bluemap.bronzedeathsquad.com/spigot/#flat:-5:-56:13:5:0.48:0.99:0:0:perspective)

2024-05-04 15:01 UTC, TBlueF requested changes
Great work! Thanks a ton for this :)
And yes, you are doing these pull requests perfectly right :D

2024-05-04 15:01 UTC, TBlueF commented on BlueMapCore/src/main/resourceExtensions/mc1_20_3/assets/minecraft/models/entity/decorated_pot.json
> +	"parent": "Made with Blockbench by TyBraniff for Bluemaps support.",
Pretty sure this was supposed to be in `"credit"` instead of `"parent"`, that might even be the reason why they are not working =)

Also a side-note on this: 
As much as i am all for giving credit to contributors, imo this is the wrong place ^^
We can keep the notes in there for now, so no need to go over all of them and remove it or something, but just so you know that they might be removed in the future for any reason :)

2024-05-04 15:01 UTC, TBlueF commented on BlueMapCore/src/main/resourceExtensions/mc1_20_3/assets/minecraft/models/entity/dragon_head.json
> +	"parent": "Made with Blockbench by TyBraniff for Bluemaps support.",
("parent" vs "credit", see previous comment)

2024-05-04 15:01 UTC, TBlueF commented on BlueMapCore/src/main/resourceExtensions/mc1_20_3/assets/minecraft/models/entity/dragon_wall_head.json
> +	"parent": "Made with Blockbench by TyBraniff for Bluemaps support.",
("parent" vs "credit", see previous comment)

2024-05-04 19:03 UTC, TyBraniff commented
Was hopeful that would fix the decorated_pot not loading right. However it didn't. Edits are made. Thanks for the catch.

2024-05-07 14:48 UTC, merged

2024-05-07 14:52 UTC, TBlueF commented
(Squash-) Merged this into my v5 branch so github retains you as the commit-author :)
I will be restructuring the resource-extensions a bit, but like this you won't have to do anything and it will be included in BlueMap v5 which i am rn working towards :)

@TyBraniff Again, awesome work, thanks a lot for this PR!

2024-06-11 17:16 UTC, Phoenix616 commented
All the non-full rotations of the hanging signs have a 0.5 offset to the true values :S (e.g. `22` should be `22.5` as it's `45/2` [here](https://github.com/BlueMap-Minecraft/BlueMap/pull/536/files#diff-83d0855d7edb9e384be37c008e81143a0afcbe1f4392fc74c18a33eba8fa56bbR40))

2024-06-11 17:20 UTC, TBlueF commented
@Phoenix616 Good catch!
If you think the effort is worth it for half a degree, please PR a fix :)